(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function ea(a,b){if(b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,g){this.a=e;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function l(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}
ea("Promise",function(a){function b(f){this.b=0;this.h=void 0;this.a=[];var k=this.c();try{f(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.a=null}function d(f){return f instanceof b?f:new b(function(k){k(f)})}if(a)return a;c.prototype.b=function(f){if(null==this.a){this.a=[];var k=this;this.c(function(){k.h()})}this.a.push(f)};var e=da.setTimeout;c.prototype.c=function(f){e(f,0)};c.prototype.h=function(){for(;this.a&&this.a.length;){var f=this.a;this.a=[];for(var k=0;k<f.length;++k){var m=
f[k];f[k]=null;try{m()}catch(p){this.f(p)}}}this.a=null};c.prototype.f=function(f){this.c(function(){throw f;})};b.prototype.c=function(){function f(p){return function(w){m||(m=!0,p.call(k,w))}}var k=this,m=!1;return{resolve:f(this.A),reject:f(this.f)}};b.prototype.A=function(f){if(f===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.F(f);else{a:switch(typeof f){case "object":var k=null!=f;break a;case "function":k=!0;break a;default:k=!1}k?this.w(f):this.i(f)}};
b.prototype.w=function(f){var k=void 0;try{k=f.then}catch(m){this.f(m);return}"function"==typeof k?this.G(k,f):this.i(f)};b.prototype.f=function(f){this.l(2,f)};b.prototype.i=function(f){this.l(1,f)};b.prototype.l=function(f,k){if(0!=this.b)throw Error("Cannot settle("+f+", "+k+"): Promise already settled in state"+this.b);this.b=f;this.h=k;this.m()};b.prototype.m=function(){if(null!=this.a){for(var f=0;f<this.a.length;++f)g.b(this.a[f]);this.a=null}};var g=new c;b.prototype.F=function(f){var k=this.c();
f.s(k.resolve,k.reject)};b.prototype.G=function(f,k){var m=this.c();try{f.call(k,m.resolve,m.reject)}catch(p){m.reject(p)}};b.prototype.then=function(f,k){function m(D,F){return"function"==typeof D?function(P){try{p(D(P))}catch(E){w(E)}}:F}var p,w,M=new b(function(D,F){p=D;w=F});this.s(m(f,p),m(k,w));return M};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.s=function(f,k){function m(){switch(p.b){case 1:f(p.h);break;case 2:k(p.h);break;default:throw Error("Unexpected state: "+
p.b);}}var p=this;null==this.a?g.b(m):this.a.push(m)};b.resolve=d;b.reject=function(f){return new b(function(k,m){m(f)})};b.race=function(f){return new b(function(k,m){for(var p=l(f),w=p.next();!w.done;w=p.next())d(w.value).s(k,m)})};b.all=function(f){var k=l(f),m=k.next();return m.done?d([]):new b(function(p,w){function M(P){return function(E){D[P]=E;F--;0==F&&p(D)}}var D=[],F=0;do D.push(void 0),F++,d(m.value).s(M(D.length-1),w),m=k.next();while(!m.done)})};return b});
function ha(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function ia(){this.l=!1;this.h=null;this.b=void 0;this.a=1;this.i=this.f=0;this.m=this.c=null}function ja(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}h=ia.prototype;h.u=function(a){this.b=a};function ka(a,b){a.c={D:b,v:!0};a.a=a.f||a.i}h.return=function(a){this.c={return:a};this.a=this.i};h.fa=function(a){this.c={j:a};this.a=this.i};
function n(a,b,c){a.a=c;return{value:b}}h.Xb=function(a,b){a=l(a);var c=a.next();ha(c);if(c.done)this.b=c.value,this.a=b;else return this.h=a,n(this,c.value,b)};h.j=function(a){this.a=a};h.ya=function(a){this.f=0;this.i=a||0};function q(a,b){a.a=b;a.f=0}function r(a){a.f=0;a.c=null}h.S=function(a,b,c){c?this.m[c]=this.c:this.m=[this.c];this.f=a||0;this.i=b||0};
h.ha=function(a,b){b=this.m.splice(b||0)[0];(b=this.c=this.c||b)?b.v?this.a=this.f||this.i:void 0!=b.j&&this.i<b.j?(this.a=b.j,this.c=null):this.a=this.i:this.a=a};h.W=function(a){return new la(a)};function la(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}la.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function ma(a){this.a=new ia;this.b=a}
function na(a,b){ja(a.a);var c=a.a.h;if(c)return oa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return t(a)}function oa(a,b,c,d){try{var e=b.call(a.a.h,c);ha(e);if(!e.done)return a.a.l=!1,e;var g=e.value}catch(f){return a.a.h=null,ka(a.a,f),t(a)}a.a.h=null;d.call(a.a,g);return t(a)}
function t(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.l=!1,{value:b.value,done:!1}}catch(c){a.a.b=void 0,ka(a.a,c)}a.a.l=!1;if(a.a.c){b=a.a.c;a.a.c=null;if(b.v)throw b.D;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function pa(a){this.next=function(b){ja(a.a);a.a.h?b=oa(a,a.a.h.next,b,a.a.u):(a.a.u(b),b=t(a));return b};this.throw=function(b){ja(a.a);a.a.h?b=oa(a,a.a.h["throw"],b,a.a.u):(ka(a.a,b),b=t(a));return b};this.return=function(b){return na(a,b)};this[Symbol.iterator]=function(){return this}}function qa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})}
function u(a){return qa(new pa(new ma(a)))}var ra=this||self;function sa(a,b){function c(){}c.prototype=b.prototype;a.La=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.I=function(d,e,g){for(var f=Array(arguments.length-2),k=2;k<arguments.length;k++)f[k-2]=arguments[k];return b.prototype[e].apply(d,f)}};var ta=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in e&&(d[g]=b.call(void 0,e[g],g,a));return d};function ua(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function va(a){if(8192>=a.length)return String.fromCharCode.apply(null,a);for(var b="",c=0;c<a.length;c+=8192)b+=String.fromCharCode.apply(null,ua(a,c,c+8192));return b};var wa={},v=null;function xa(a,b){void 0===b&&(b=0);ya();b=wa[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],g=d+1<a.length,f=g?a[d+1]:0,k=d+2<a.length,m=k?a[d+2]:0,p=e>>2;e=(e&3)<<4|f>>4;f=(f&15)<<2|m>>6;m&=63;k||(m=64,g||(f=64));c.push(b[p],b[e],b[f]||"",b[m]||"")}return c.join("")}function za(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):-1!="=.".indexOf(a[b-1])&&(c=-1!="=.".indexOf(a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Aa(a,function(g){d[e++]=g});return d.subarray(0,e)}
function Aa(a,b){function c(m){for(;d<a.length;){var p=a.charAt(d++),w=v[p];if(null!=w)return w;if(!/^[\s\xa0]*$/.test(p))throw Error("Unknown base64 encoding at char: "+p);}return m}ya();for(var d=0;;){var e=c(-1),g=c(0),f=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|g>>4);64!=f&&(b(g<<4&240|f>>2),64!=k&&b(f<<6&192|k))}}
function ya(){if(!v){v={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));wa[c]=d;for(var e=0;e<d.length;e++){var g=d[e];void 0===v[g]&&(v[g]=e)}}}};var x=0,y=0;function Ba(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;x=b;y=a}function z(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));x=c;y=a}function Ca(a){var b=0>a;a=2*Math.abs(a);Ba(a);a=x;var c=y;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);x=a;y=c}
function Da(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?x=y=0:(y=0,x=2147483648);else if(isNaN(a))y=0,x=2147483647;else if(3.4028234663852886E38<a)y=0,x=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),y=0,x=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;y=0;x=(b<<31|c+127<<23|a)>>>0}}
function Ea(a){var b=a.charCodeAt(4),c=a.charCodeAt(5),d=a.charCodeAt(6),e=a.charCodeAt(7);x=a.charCodeAt(0)+(a.charCodeAt(1)<<8)+(a.charCodeAt(2)<<16)+(a.charCodeAt(3)<<24)>>>0;y=b+(c<<8)+(d<<16)+(e<<24)>>>0}function Fa(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function Ga(a){function b(f,k){for(var m=0;8>m&&(1!==f||0<k);m++)k=f*e[m]+k,e[m]=k&255,k>>>=8}function c(){for(var f=0;8>f;f++)e[f]=~e[f]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],g=0;g<a.length;g++)b(10,a.charCodeAt(g)-48);d&&(c(),b(1,1));return va(e)};function A(a,b){this.a=a;this.b=b}function Ia(a){return new A((a.a>>>1|(a.b&1)<<31)>>>0,a.b>>>1>>>0)}function Ja(a){return new A(a.a<<1>>>0,(a.b<<1|a.a>>>31)>>>0)}h=A.prototype;h.ia=function(){return!!(this.a&1)};h.add=function(a){return new A((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};h.sub=function(a){return new A((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};
function Ka(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new A(a>>>0,b>>>0)}h.toString=function(){for(var a="",b=this;0!=b.a||0!=b.b;){var c=new A(0,0);b=new A(b.a,b.b);for(var d=new A(10,0),e=new A(1,0);!(d.b&2147483648);)d=Ja(d),e=Ja(e);for(;0!=e.a||0!=e.b;)0>=(d.b<b.b||d.b==b.b&&d.a<b.a?-1:d.b==b.b&&d.a==b.a?0:1)&&(c=c.add(e),b=b.sub(d)),d=Ia(d),e=Ia(e);c=[c,b];b=c[0];a=c[1].a+a}""==a&&(a="0");return a};
function B(a){for(var b=new A(0,0),c=new A(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.a=parseInt(a[d],10);var e=Ka(b.a);b=Ka(b.b);b.b=b.a;b.a=0;b=e.add(b).add(c)}return b}h.ea=function(){return new A(this.a,this.b)};function C(a,b){this.a=a;this.b=b}C.prototype.add=function(a){return new C((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};
C.prototype.sub=function(a){return new C((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};C.prototype.c=function(){return new C(this.a,this.b)};C.prototype.toString=function(){var a=0!=(this.b&2147483648),b=new A(this.a,this.b);a&&(b=(new A(0,0)).sub(b));return(a?"-":"")+b.toString()};function La(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=B(a);if(null===a)return null;b&&(a=(new A(0,0)).sub(a));return new C(a.a,a.b)};function Ma(){this.a=[]}h=Ma.prototype;h.length=function(){return this.a.length};function G(a){var b=a.a;a.a=[];return b}function I(a,b,c){for(;0<c||127<b;)a.a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.a.push(b)}function J(a,b,c){K(a,b);K(a,c)}function Na(a,b,c){Fa(b,c,function(d,e){I(a,d>>>0,e>>>0)})}function L(a,b){for(;127<b;)a.a.push(b&127|128),b>>>=7;a.a.push(b)}function N(a,b){if(0<=b)L(a,b);else{for(var c=0;9>c;c++)a.a.push(b&127|128),b>>=7;a.a.push(1)}}
function Oa(a,b){L(a,(b<<1^b>>31)>>>0)}function Pa(a,b){Ea(Ga(b));Fa(x,y,function(c,d){I(a,c>>>0,d>>>0)})}h.Wb=function(a){this.a.push(a>>>0&255)};h.Vb=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};function K(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}function Qa(a,b){Ba(b);K(a,x);K(a,y)}h.Ra=function(a){this.a.push(a>>>0&255)};h.Qa=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};
function Ra(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}
function Sa(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)y=0<1/c?0:2147483648,x=0;else if(isNaN(c))y=2147483647,x=4294967295;else if(1.7976931348623157E308<c)y=(b<<31|2146435072)>>>0,x=0;else if(2.2250738585072014E-308>c)c/=Math.pow(2,-1074),y=(b<<31|c/4294967296)>>>0,x=c>>>0;else{var d=c,e=0;if(2<=d)for(;2<=d&&1023>e;)e++,d/=2;else for(;1>d&&-1022<e;)d*=2,e--;c*=Math.pow(2,-e);y=(b<<31|e+1023<<20|1048576*c&1048575)>>>0;x=4503599627370496*c>>>0}K(a,x);K(a,y)}
h.aa=function(a){this.a.push.apply(this.a,a)};function Ta(){this.c=[];this.b=0;this.a=new Ma;this.f=[]}function Ua(a,b){var c=G(a.a);a.c.push(c);a.c.push(b);a.b+=c.length+b.length}function O(a,b){Q(a,b,2);b=G(a.a);a.c.push(b);a.b+=b.length;b.push(a.b);return b}function R(a,b){var c=b.pop();for(c=a.b+a.a.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.b++;b.push(c);a.b++}h=Ta.prototype;h.ja=function(a,b,c){null!=a&&null!=b&&null!=c&&Ua(this,a.subarray(b,c))};h.ba=function(){this.c=[];G(this.a);this.b=0;this.f=[]};
function Va(a){for(var b=new Uint8Array(a.b+a.a.length()),c=a.c,d=c.length,e=0,g=0;g<d;g++){var f=c[g];b.set(f,e);e+=f.length}c=G(a.a);b.set(c,e);a.c=[b];return b}h.Y=function(a){return xa(Va(this),a)};h.J=function(a){this.f.push(O(this,a))};h.R=function(){R(this,this.f.pop())};function Q(a,b,c){L(a.a,8*b+c)}
h.Oa=function(a,b,c){switch(a){case 1:null!=c&&(Q(this,b,1),Sa(this.a,c));break;case 2:null!=c&&(Q(this,b,5),a=this.a,Da(c),K(a,x));break;case 3:null!=c&&null!=c&&(Q(this,b,0),a=this.a,z(c),I(a,x,y));break;case 4:null!=c&&null!=c&&(Q(this,b,0),a=this.a,z(c),I(a,x,y));break;case 5:null!=c&&Wa(this,b,c);break;case 6:null!=c&&(Q(this,b,1),Qa(this.a,c));break;case 7:null!=c&&(Q(this,b,5),K(this.a,c));break;case 8:S(this,b,c);break;case 9:T(this,b,c);break;case 12:Xa(this,b,c);break;case 13:null!=c&&Ya(this,
b,c);break;case 14:Za(this,b,c);break;case 15:null!=c&&(Q(this,b,5),Ra(this.a,c));break;case 16:null!=c&&(Q(this,b,1),a=this.a,z(c),J(a,x,y));break;case 17:null!=c&&null!=c&&(Q(this,b,0),Oa(this.a,c));break;case 18:null!=c&&null!=c&&(Q(this,b,0),a=this.a,Ca(c),I(a,x,y))}};function Ya(a,b,c){null!=c&&(Q(a,b,0),L(a.a,c))}function Wa(a,b,c){null!=c&&(Q(a,b,0),N(a.a,c))}h.Ub=function(a,b){null!=b&&null!=b&&(Q(this,a,0),Pa(this.a,b))};function S(a,b,c){null!=c&&(Q(a,b,0),a.a.a.push(c?1:0))}
function Za(a,b,c){null!=c&&(Q(a,b,0),N(a.a,c))}
function T(a,b,c){if(null!=c){b=O(a,b);for(var d=a.a,e=0;e<c.length;e++){var g=c.charCodeAt(e);if(128>g)d.a.push(g);else if(2048>g)d.a.push(g>>6|192),d.a.push(g&63|128);else if(65536>g)if(55296<=g&&56319>=g&&e+1<c.length){var f=c.charCodeAt(e+1);56320<=f&&57343>=f&&(g=1024*(g-55296)+f-56320+65536,d.a.push(g>>18|240),d.a.push(g>>12&63|128),d.a.push(g>>6&63|128),d.a.push(g&63|128),e++)}else d.a.push(g>>12|224),d.a.push(g>>6&63|128),d.a.push(g&63|128)}R(a,b)}}
function Xa(a,b,c){null!=c&&(c=c.constructor===Uint8Array?c:c.constructor===ArrayBuffer?new Uint8Array(c):c.constructor===Array?new Uint8Array(c):c.constructor===String?za(c):new Uint8Array(0),Q(a,b,2),L(a.a,c.length),Ua(a,c))}h.Sa=function(a,b,c){null!=b&&(a=O(this,a),c(b,this),R(this,a))};h.Ta=function(a,b,c){null!=b&&(Q(this,1,3),Q(this,2,0),N(this.a,a),a=O(this,3),c(b,this),R(this,a),Q(this,1,4))};h.Pa=function(a,b,c){null!=b&&(Q(this,a,3),c(b,this),Q(this,a,4))};
h.Bb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Wa(this,a,b[c])};h.Cb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Wa(this,a,parseInt(d,10))}};h.Db=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){Q(this,a,0);var e=this.a;z(d);I(e,x,y)}}};h.Mb=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),f=d(b[e]);Q(this,a,1);J(this.a,g,f)}};
h.Nb=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),f=d(b[e]);Q(this,a,0);I(this.a,g,f)}};h.Ob=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),f=d(b[e]);Q(this,a,0);Na(this.a,g>>>0,f>>>0)}};h.Eb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=La(e),Q(this,d,0),I(this.a,e.a,e.b))}};h.Qb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Ya(this,a,b[c])};
h.Rb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Ya(this,a,parseInt(d,10))}};h.Sb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){Q(this,a,0);var e=this.a;z(d);I(e,x,y)}}};h.Tb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=B(e),Q(this,d,0),I(this.a,e.a,e.b))}};h.Jb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(Q(this,a,0),Oa(this.a,d))}};
h.Kb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){Q(this,a,0);var e=this.a;Ca(d);I(e,x,y)}}};h.Lb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(Q(this,a,0),Pa(this.a,d))}};h.wb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(Q(this,a,5),K(this.a,d))}};h.xb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(Q(this,a,1),Qa(this.a,d))}};
h.yb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=B(e),Q(this,d,1),J(this.a,e.a,e.b))}};h.Gb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(Q(this,a,5),Ra(this.a,d))}};h.Hb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){Q(this,a,1);var e=this.a;z(d);J(e,x,y)}}};h.Ib=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=La(e),Q(this,d,1),J(this.a,e.a,e.b))}};
h.zb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){Q(this,a,5);var e=this.a;Da(d);K(e,x)}}};h.ub=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(Q(this,a,1),Sa(this.a,d))}};h.sb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)S(this,a,b[c])};h.vb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Za(this,a,b[c])};h.Pb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)T(this,a,b[c])};
h.tb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Xa(this,a,b[c])};h.Fb=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=O(this,a);c(b[d],this);R(this,e)}};h.Ab=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)Q(this,a,3),c(b[d],this),Q(this,a,4)};h.ab=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++)N(this.a,b[c]);R(this,a)}};h.bb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++)N(this.a,parseInt(b[c],10));R(this,a)}};
h.cb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++){var d=this.a;z(b[c]);I(d,x,y)}R(this,a)}};h.lb=function(a,b,c,d){if(null!=b){a=O(this,a);for(var e=0;e<b.length;e++)J(this.a,c(b[e]),d(b[e]));R(this,a)}};h.mb=function(a,b,c,d){if(null!=b){a=O(this,a);for(var e=0;e<b.length;e++)I(this.a,c(b[e]),d(b[e]));R(this,a)}};h.nb=function(a,b,c,d){if(null!=b){a=O(this,a);for(var e=this.a,g=0;g<b.length;g++)Na(e,c(b[g]),d(b[g]));R(this,a)}};
h.eb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++){var d=La(b[c]);I(this.a,d.a,d.b)}R(this,a)}};h.ob=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++)L(this.a,b[c]);R(this,a)}};h.pb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++)L(this.a,parseInt(b[c],10));R(this,a)}};h.qb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++){var d=this.a;z(b[c]);I(d,x,y)}R(this,a)}};
h.rb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++){var d=B(b[c]);I(this.a,d.a,d.b)}R(this,a)}};h.ib=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++)Oa(this.a,b[c]);R(this,a)}};h.jb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++){var d=this.a;Ca(b[c]);I(d,x,y)}R(this,a)}};h.kb=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++)Pa(this.a,b[c]);R(this,a)}};
h.Xa=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,4*b.length),a=0;a<b.length;a++)K(this.a,b[a])};h.Ya=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,8*b.length),a=0;a<b.length;a++)Qa(this.a,b[a])};h.Za=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,8*b.length),a=0;a<b.length;a++){var c=B(b[a]);J(this.a,c.a,c.b)}};h.fb=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,4*b.length),a=0;a<b.length;a++)Ra(this.a,b[a])};
h.gb=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;z(b[a]);J(c,x,y)}};h.hb=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;Ea(Ga(b[a]));J(c,x,y)}};h.$a=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,4*b.length),a=0;a<b.length;a++){var c=this.a;Da(b[a]);K(c,x)}};h.Va=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,8*b.length),a=0;a<b.length;a++)Sa(this.a,b[a])};
h.Ua=function(a,b){if(null!=b&&b.length)for(Q(this,a,2),L(this.a,b.length),a=0;a<b.length;a++)this.a.a.push(b[a]?1:0)};h.Wa=function(a,b){if(null!=b&&b.length){a=O(this,a);for(var c=0;c<b.length;c++)N(this.a,b[c]);R(this,a)}};function $a(){}var ab="function"==typeof Uint8Array;$a.prototype.m=function(){return this.i};function bb(a,b){a.c=null;b||(b=[]);a.i=void 0;a.f=-1;a.a=b;a:{if(b=a.a.length){--b;var c=a.a[b];if(!(null===c||"object"!=typeof c||Array.isArray(c)||ab&&c instanceof Uint8Array)){a.h=b-a.f;a.b=c;break a}}a.h=Number.MAX_VALUE}a.l={}}var cb=[];function db(a){var b=a.h+a.f;a.a[b]||(a.b=a.a[b]={})}
function eb(a,b){if(b<a.h){b+=a.f;var c=a.a[b];return c===cb?a.a[b]=[]:c}if(a.b)return c=a.b[b],c===cb?a.b[b]=[]:c}function U(a,b,c){a=eb(a,b);return null==a?c:a}function V(a,b){a=eb(a,b);a=null==a?a:!!a;return null==a?!1:a}function W(a,b,c){return X(a,b,c,"")}function X(a,b,c,d){c!==d?b<a.h?a.a[b+a.f]=c:(db(a),a.b[b]=c):b<a.h?a.a[b+a.f]=null:(db(a),delete a.b[b]);return a}h=$a.prototype;
h.Ma=function(){if(this.c)for(var a in this.c){var b=this.c[a];if(Array.isArray(b))for(var c=0;c<b.length;c++);}};h.B=ab?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return xa(this)};try{return JSON.stringify(this.a&&this.a,fb)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.a&&this.a,fb)};function fb(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)}
function gb(a,b){return new a(b?JSON.parse(b):null)}h.toString=function(){return this.a.toString()};h.da=function(a){db(this);this.c||(this.c={});var b=a.c;return a.f?a.a()?(this.c[b]||(this.c[b]=ta(this.b[b]||[],function(c){return new a.b(c)})),this.c[b]):this.b[b]=this.b[b]||[]:a.a()?(!this.c[b]&&this.b[b]&&(this.c[b]=new a.b(this.b[b])),this.c[b]):this.b[b]};
h.xa=function(a,b){this.c||(this.c={});db(this);var c=a.c;a.f?(b=b||[],a.a()?(this.c[c]=b,this.b[c]=ta(b,function(d){return d.a})):this.b[c]=b):a.a()?(this.c[c]=b,this.b[c]=b?b.a:b):this.b[c]=b;return this};h.N=function(){return new this.constructor(hb(this.a))};h.ca=function(){return new this.constructor(hb(this.a))};
function hb(a){if(Array.isArray(a)){for(var b=Array(a.length),c=0;c<a.length;c++){var d=a[c];null!=d&&(b[c]="object"==typeof d?hb(d):d)}return b}if(ab&&a instanceof Uint8Array)return new Uint8Array(a);b={};for(c in a)d=a[c],null!=d&&(b[c]="object"==typeof d?hb(d):d);return b};function ib(a){bb(this,a)}sa(ib,$a);h=ib.prototype;h.oa=function(a){var b={ga:U(this,1,""),Z:U(this,2,""),body:U(this,3,""),M:U(this,4,""),V:U(this,5,""),T:U(this,6,""),U:U(this,7,""),ka:U(this,8,""),Na:U(this,9,""),P:V(this,10),O:V(this,11),ma:U(this,12,0),lang:U(this,13,""),H:U(this,14,""),la:U(this,15,""),L:U(this,16,""),K:U(this,17,""),$:V(this,21),X:V(this,23),dir:U(this,24,"")};a&&(b.C=this);return b};
h.na=function(){var a=new Ta;var b=U(this,1,"");0<b.length&&T(a,1,b);b=U(this,2,"");0<b.length&&T(a,2,b);b=U(this,3,"");0<b.length&&T(a,3,b);b=U(this,4,"");0<b.length&&T(a,4,b);b=U(this,5,"");0<b.length&&T(a,5,b);b=U(this,6,"");0<b.length&&T(a,6,b);b=U(this,7,"");0<b.length&&T(a,7,b);b=U(this,8,"");0<b.length&&T(a,8,b);b=U(this,9,"");0<b.length&&T(a,9,b);(b=V(this,10))&&S(a,10,b);(b=V(this,11))&&S(a,11,b);b=U(this,12,0);0!==b&&Za(a,12,b);b=U(this,13,"");0<b.length&&T(a,13,b);b=U(this,14,"");0<b.length&&
T(a,14,b);b=U(this,15,"");0<b.length&&T(a,15,b);b=U(this,16,"");0<b.length&&T(a,16,b);b=U(this,17,"");0<b.length&&T(a,17,b);(b=V(this,21))&&S(a,21,b);(b=V(this,23))&&S(a,23,b);b=U(this,24,"");0<b.length&&T(a,24,b);return Va(a)};h.Ga=function(a){return W(this,1,a)};h.Da=function(a){return W(this,2,a)};h.qa=function(a){return W(this,3,a)};h.ta=function(a){return W(this,4,a)};h.Ba=function(a){return W(this,5,a)};h.za=function(a){return W(this,6,a)};h.Aa=function(a){return W(this,7,a)};
h.Ha=function(a){return W(this,8,a)};h.Ka=function(a){return W(this,9,a)};h.wa=function(a){return X(this,10,a,!1)};h.va=function(a){return X(this,11,a,!1)};h.Ja=function(a){return X(this,12,a,0)};h.Fa=function(a){return W(this,13,a)};h.pa=function(a){return W(this,14,a)};h.Ia=function(a){return W(this,15,a)};h.sa=function(a){return W(this,16,a)};h.ra=function(a){return W(this,17,a)};h.Ea=function(a){return X(this,21,a,!1)};h.Ca=function(a){return X(this,23,a,!1)};
h.ua=function(a){return W(this,24,a)};var jb=[/^https:\/\/cloud.google.com\/blog.*/,/\.pdf$/,/\.mp4$/];function kb(){this.a=null;this.b=!1;try{lb(this)}catch(a){console.warn(a)}}function lb(a){return a.b?Promise.resolve():new Promise(function(b){var c=ra.indexedDB.open("devsite-index-db",1);c.onsuccess=function(){a.a=c.result;a.b=!0;b()};c.onerror=function(d){throw Error(d);};c.onupgradeneeded=function(d){d=d.target.result.createObjectStore("userPreferences",{keyPath:"name"});d.createIndex("name","name",{unique:!0});d.createIndex("value","value",{unique:!1})}})}
kb.prototype.set=function(a,b){var c=this,d,e;return u(function(g){if(1==g.a)return n(g,lb(c),2);try{return d=c.a.transaction(["userPreferences"],"readwrite"),e={},d.objectStore("userPreferences").put((e.name=a,e.value=b,e)),g.return(new Promise(function(f){d.oncomplete=f}))}catch(f){console.warn(f)}g.a=0})};
kb.prototype.get=function(a){var b=this,c,d;return u(function(e){if(1==e.a)return n(e,lb(b),2);try{return c=b.a.transaction(["userPreferences"],"readwrite"),d=c.objectStore("userPreferences").get(a),e.return(new Promise(function(g){d.onsuccess=function(){g(d.result?d.result.value:void 0)}}))}catch(g){console.warn(g)}e.a=0})};var mb=["content-length","etag","last-modified"];function nb(a){a=new URL(a);return["fonts.googleapis.com","localhost"].includes(a.hostname)?!0:["www.gstatic.com","gsatic.com"].includes(a.hostname)?a.pathname.startsWith("/devrel-devsite/"):!1};function Y(a){bb(this,a)}sa(Y,$a);Y.prototype.A=function(a){var b={action:U(this,1,0),url:U(this,2,"")};a&&(b.C=this);return b};Y.prototype.w=function(){var a=new Ta;var b=U(this,1,0);0!==b&&Za(a,1,b);b=U(this,2,"");0<b.length&&T(a,2,b);return Va(a)};function ob(a){var b=new Y;return X(b,1,a,0)};function pb(a,b){this.g=a;this.a=b;this.b=new kb}function qb(a){var b=Z(a);return!(-1<b.pathname.split("/").pop().indexOf("."))&&b.origin===a.g.location.origin}function Z(a){return new URL(a.a.url,a.g.location.origin)}function rb(a){var b=Z(a);return qb(a)&&b.searchParams.has("partial")}function sb(a){return u(function(b){return b.return(a.g.caches.open("devsite.pwa_RUNTIME_v2"))})}
function tb(a){var b,c,d,e;return u(function(g){if(1==g.a)return n(g,a.text(),2);b=g.b;try{c=gb(ib,b)}catch(f){}d=new Headers(a.headers);d.set("Content-Type","text/html");e={status:a.status,statusText:a.statusText,headers:d};return c?g.return(new Response(U(c,1,""),e)):g.return(new Response(b,e))})}
function ub(a,b){var c,d;return u(function(e){if(1==e.a)return c=new URL(b),c.searchParams.has("hl")?e.return(c):qb(a)?n(e,a.b.get("language_preference"),3):e.j(2);2!=e.a&&(d=e.b,c.searchParams.set("hl",d||"en"));return e.return(c)})}
function vb(a){var b,c,d,e,g;return u(function(f){switch(f.a){case 1:return n(f,sb(a),2);case 2:return b=f.b,c=Z(a),n(f,ub(a,c.href),3);case 3:d=f.b;if(!qb(a)||rb(a)){f.j(4);break}e=new URL(d.href);e.searchParams.set("partial","1");return n(f,b.match(e.href),5);case 5:if(g=f.b)return f.return(Promise.resolve(tb(g)));case 4:return f.return(b.match(d.href))}})}
function wb(a,b){return a&&b?mb.some(function(c){return a.headers.has(c)&&b.headers.has(c)})?mb.every(function(c){return a.headers.has(c)===b.headers.has(c)&&a.headers.get(c)===b.headers.get(c)}):!1:!1}function xb(a,b){var c,d;u(function(e){if(1==e.a)return c=b.B(),n(e,a.g.clients.matchAll(),2);d=e.b;d.forEach(function(g){g.postMessage(c)});e.a=0})}
function yb(a){var b,c,d,e;return u(function(g){switch(g.a){case 1:return n(g,sb(a),2);case 2:return b=g.b,n(g,ub(a,a.a.url),3);case 3:return c=g.b,n(g,b.match(c.href),4);case 4:return d=g.b,e=a.g.fetch(a.a).then(function(f){if(f&&(b.put(c.href,f.clone()),d&&Z(a).pathname.match(/\.(jpeg|jpg|gif|png|svg|webp|avi|mp4|mov)$/)&&!wb(d,f)&&Array.from(f.headers.keys()).length)){var k=ob(2);k=W(k,2,a.a.url);xb(a,k)}return f}).catch(function(){return zb()}),g.return(d||e)}})}
pb.prototype.fetch=function(){var a=this,b;return u(function(c){if(1==c.a){if("GET"!==a.a.method)var d=!1;else d=Z(a),d=d.hostname===a.g.location.hostname?!0:nb(d.href);return d?n(c,vb(a),2):c.return(a.g.fetch(a.a))}if(d=b=c.b){d=b.headers.get("date");var e=b.headers.get("expires"),g=new Date(d),f=new Date(e);e=e&&0>Date.now()-f.getTime();d=!!(d&&6E4>Date.now()-g.getTime()||e)}d?c=c.return(Promise.resolve(b)):(g=Z(a),d=!!g.pathname.match(/\.(jpeg|jpg|gif|png|svg|webp|avi|mp4|mov|css|js)$/),g=g.origin===
a.g.location.origin||nb(g.href),c=d&&g?c.return(yb(a)):c.return(Ab(a)));return c})};function Bb(a,b){var c,d;return u(function(e){switch(e.a){case 1:return n(e,sb(a),2);case 2:c=e.b;if(!c){e.j(0);break}e.f=4;return n(e,ub(a,a.a.url),6);case 6:d=e.b;b.ok?c.put(d.href,b.clone()):404===b.status&&c.delete(d.href);q(e,0);break;case 4:r(e),e.a=0}})}
function zb(){return new Response("<h1>Service Unavailable</h1>",{status:503,statusText:"Service Unavailable",headers:new Headers({"Content-Type":"text/html"})})}
function Ab(a){var b,c,d,e,g;return u(function(f){switch(f.a){case 1:return f.f=2,n(f,a.g.fetch(a.a.clone()),4);case 4:return(b=f.b)?n(f,Bb(a,b),8):n(f,vb(a),7);case 7:return(c=f.b)?f.return(c):f.return(zb());case 8:return f.return(b);case 6:q(f,0);break;case 2:return r(f),n(f,vb(a),9);case 9:if(d=f.b)return f.return(d);if(!qb(a)){f.j(10);break}return n(f,sb(a),11);case 11:return e=f.b,n(f,e.match("/_static/offline?partial=1"),12);case 12:if(g=f.b)return rb(a)?f.return(g):f.return(tb(g));case 10:return f.return(zb())}})}
;var Cb=[/^utm_/,/^dcb_$/];function Db(a){this.g=a;this.c="1.1";this.a={};Eb(this)}function Fb(a){var b,c;return u(function(d){if(1==d.a)return n(d,a.g.caches.keys(),2);b=d.b;c=b.filter(function(e){return"devsite.pwa_RUNTIME_v2"!==e});return n(d,Promise.all(c.map(function(e){return a.g.caches.delete(e)})),0)})}
function Eb(a){var b;u(function(c){if(1==c.a)return a.a["devsite.pwa_RUNTIME_v2"]?c.return(a.a["devsite.pwa_RUNTIME_v2"]):n(c,a.g.caches.open("devsite.pwa_RUNTIME_v2"),2);b=c.b;a.a["devsite.pwa_RUNTIME_v2"]=b;return c.return(b)})}function Gb(a){return!("navigate"!==a.mode&&!a.headers.get("Upgrade-Insecure-Requests")&&-1===(a.headers.get("Accept")||"").indexOf("text/html"))}
function Hb(a,b){var c,d,e,g,f,k,m,p,w,M,D,F,P,E;return u(function(H){switch(H.a){case 1:c=b.clone();d=new URL(b.url,a.g.location.origin);if(Gb(b)||d.origin!==a.g.location.origin&&!nb(d.href))return H.return(Promise.resolve(c));d.hash="";e=Array.from(d.searchParams);g={};f=l(e);for(k=f.next();!k.done;g={o:g.o},k=f.next())m=k.value,p=l(m),g.o=p.next().value,p.next(),Cb.forEach(function(Ha){return function(Jb){Ha.o.match(Jb)&&d.searchParams.delete(Ha.o)}}(g));w=new Headers;M=l(b.headers.entries());
for(D=M.next();!D.done;D=M.next())F=D.value,F[1]&&w.append(F[0],F[1]);H.f=2;return n(H,b.text(),4);case 4:P=H.b;q(H,3);break;case 2:return r(H),H.return(Promise.resolve(c));case 3:E={};E.method=b.method;E.mode=b.mode;E.body=P;E.redirect=b.redirect;E.headers=w;E.credentials=b.credentials;E.cache=b.cache;E.referrer=b.referrer;try{return H.return(Promise.resolve(new Request(d.href,E)))}catch(Ha){return H.return(Promise.resolve(c))}}})}
function Ib(a,b){var c,d;return u(function(e){if(1==e.a)return n(e,Hb(a,b.clone()),2);c=e.b;d=new pb(a.g,c);return e.return(d.fetch())})}Db.prototype.b=function(a){console.log("[ServiceWorker] Network unavailable",a)};
function Kb(a,b){var c,d,e,g,f,k,m;u(function(p){if(1==p.a)return c=a.g.location,d=c.origin,e=new URL(b,c.origin),g=e.origin,f=e.pathname,k={},nb(e.href)||0===f.indexOf("/_static")?k.mode="cors":g===d?k.credentials="include":k.mode="no-cors",m=new Request(b,k),p.f=2,n(p,Ib(a,m),4);if(2!=p.a)return q(p,0);r(p);return p.return()})};function Lb(a,b){var c="POST"===b.request.method||b.request.headers.has("range");jb.find(function(d){return d.test(b.request.url)})&&(c=!0);c||b.respondWith(Ib(a.a,b.request))}function Mb(a,b){b.waitUntil(Fb(a.a).then(function(){return a.g.clients.claim()}).then(function(){var c,d,e;return u(function(g){if(1==g.a)return c=ob(4),d=c.B(),n(g,a.g.clients.matchAll({type:"window"}),2);e=g.b;e.forEach(function(f){f.postMessage(d)});g.a=0})}))}
function Nb(a,b){var c,d,e;return u(function(g){if(1==g.a){c=b;try{d=gb(Y,c.data)}catch(f){return g.return()}switch(U(d,1,0)){case 1:Kb(a.a,U(d,2,""));break;case 3:return g.j(2)}return g.j(0)}if(4!=g.a)return n(g,a.g.clients.matchAll({type:"window"}),4);e=g.b;e.forEach(function(f){f.id!==c.source.id&&f.postMessage(c.data)});return g.j(0)})};new function(){var a=self,b=this;this.g=a;this.a=new Db(a);this.g.addEventListener("install",function(c){c.waitUntil(b.g.skipWaiting())},!1);this.g.addEventListener("fetch",function(c){return Lb(b,c)},!1);this.g.addEventListener("activate",function(c){return Mb(b,c)},!1);this.g.addEventListener("message",function(c){return Nb(b,c)},!1)};}).call(this);
